In [1]:
import torch

In [2]:
torch.__version__

'1.13.0'

In [3]:
from sys import version
version

'3.10.10 (main, Feb 16 2023, 02:49:39) [Clang 14.0.0 (clang-1400.0.29.202)]'

In [4]:
# INDEXING WITH LISTS
t = torch.randn((2,5))
print(t)
print(t[1])
print(t[[0,0,1]])

# INDEXING WITH TENSORS
print(t[torch.tensor([0,1,1])])

tensor([[-0.0367,  0.1352,  1.4140,  1.1487,  0.0682],
        [ 1.5544, -0.1197,  0.5457, -1.3996, -2.5171]])
tensor([ 1.5544, -0.1197,  0.5457, -1.3996, -2.5171])
tensor([[-0.0367,  0.1352,  1.4140,  1.1487,  0.0682],
        [-0.0367,  0.1352,  1.4140,  1.1487,  0.0682],
        [ 1.5544, -0.1197,  0.5457, -1.3996, -2.5171]])
tensor([[-0.0367,  0.1352,  1.4140,  1.1487,  0.0682],
        [ 1.5544, -0.1197,  0.5457, -1.3996, -2.5171],
        [ 1.5544, -0.1197,  0.5457, -1.3996, -2.5171]])


In [15]:
# INDEXING WITH TENSORS IN MULTIPLE DIMENSIONS
# https://youtu.be/TCH_1BHY58I?t=1028
x = torch.arange(12).reshape(3, 4)
print("x:\n", x)

y = torch.tensor([[0, 2], [1, 1], [2, 0]])
print("y:\n", y)

print("indexes:\n", y[:, 0], y[:, 1])
result = x[y[:, 0], y[:, 1]]
print("result:\n", result) # do you see it?

x:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
y:
 tensor([[0, 2],
        [1, 1],
        [2, 0]])
indexes:
 tensor([0, 1, 2]) tensor([2, 1, 0])
result:
 tensor([2, 5, 8])


In [31]:
# more fun example from karpathy
C = torch.randn((27,2))
X = torch.arange(32*3).reshape((32,3)) % 27 # thank you chatgpt for the % 27
C.shape, X.shape, C[X].shape
# if you understand this, you can explain why the % 27 is needed

(torch.Size([27, 2]), torch.Size([32, 3]), torch.Size([32, 3, 2]))