In [2]:
import torch

In [3]:
torch.__version__

'2.0.0'

In [4]:
from sys import version
version

'3.10.8 (main, Nov 30 2022, 20:34:09) [Clang 14.0.0 (clang-1400.0.29.202)]'

In [5]:
# INDEXING WITH LISTS
t = torch.randn((2,5))
print(t)
print(t[1])
print(t[[0,0,1]])

# INDEXING WITH TENSORS
print(t[torch.tensor([0,1,1])])

tensor([[ 0.3618, -1.3915,  1.3525, -0.5078, -0.1234],
        [-1.5954, -0.6736, -1.3406, -0.2966,  0.3060]])
tensor([-1.5954, -0.6736, -1.3406, -0.2966,  0.3060])
tensor([[ 0.3618, -1.3915,  1.3525, -0.5078, -0.1234],
        [ 0.3618, -1.3915,  1.3525, -0.5078, -0.1234],
        [-1.5954, -0.6736, -1.3406, -0.2966,  0.3060]])
tensor([[ 0.3618, -1.3915,  1.3525, -0.5078, -0.1234],
        [-1.5954, -0.6736, -1.3406, -0.2966,  0.3060],
        [-1.5954, -0.6736, -1.3406, -0.2966,  0.3060]])


In [6]:
# INDEXING WITH TENSORS IN MULTIPLE DIMENSIONS
# https://youtu.be/TCH_1BHY58I?t=1028
x = torch.arange(12).reshape(3, 4)
print("x:\n", x)

y = torch.tensor([[0, 2], [1, 1], [2, 0]])
print("y:\n", y)

print("indexes:\n", y[:, 0], y[:, 1])
result = x[y[:, 0], y[:, 1]]
print("result:\n", result) # do you see it?

x:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
y:
 tensor([[0, 2],
        [1, 1],
        [2, 0]])
indexes:
 tensor([0, 1, 2]) tensor([2, 1, 0])
result:
 tensor([2, 5, 8])


In [7]:
# more fun example from karpathy
C = torch.randn((27,2))
X = torch.arange(32*3).reshape((32,3)) % 27 # thank you chatgpt for the % 27
C.shape, X.shape, C[X].shape
# if you understand this, you can explain why the % 27 is needed

(torch.Size([27, 2]), torch.Size([32, 3]), torch.Size([32, 3, 2]))

In [11]:
# CONCATENATE
X = torch.randn((2,3))
X, torch.cat((x, x), 0), torch.cat((x, x), 1)

(tensor([[ 0.6765,  0.4935, -1.0757],
         [-0.9102, -0.0028,  1.3598]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3,  0,  1,  2,  3],
         [ 4,  5,  6,  7,  4,  5,  6,  7],
         [ 8,  9, 10, 11,  8,  9, 10, 11]]))