In [51]:
## VERSION
from sys import version
import torch
torch.manual_seed(42)
version, torch.__version__

('3.10.8 (main, Nov 30 2022, 20:34:09) [Clang 14.0.0 (clang-1400.0.29.202)]',
 '2.0.0')

In [52]:
# INDEXING WITH LISTS & TENSORS IN ONE DIMENSION
t = torch.randn((2,5))
t, t[1], t[[0,0,1]], t[torch.tensor([0,1,1])]

(tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229],
         [-0.1863,  2.2082, -0.6380,  0.4617,  0.2674]]),
 tensor([-0.1863,  2.2082, -0.6380,  0.4617,  0.2674]),
 tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229],
         [ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229],
         [-0.1863,  2.2082, -0.6380,  0.4617,  0.2674]]),
 tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229],
         [-0.1863,  2.2082, -0.6380,  0.4617,  0.2674],
         [-0.1863,  2.2082, -0.6380,  0.4617,  0.2674]]))

In [53]:
# INDEXING WITH TENSORS IN MULTIPLE DIMENSIONS
x = torch.arange(12).reshape(3, 4)
y = torch.tensor([[0, 2], [1, 1], [2, 0]])
x, y, y[:, 0], y[:, 1], x[y[:, 0], y[:, 1]]  # do you see it for the last one?

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[0, 2],
         [1, 1],
         [2, 0]]),
 tensor([0, 1, 2]),
 tensor([2, 1, 0]),
 tensor([2, 5, 8]))

In [54]:
# more fun example from karpathy https://youtu.be/TCH_1BHY58I?t=1028
C = torch.randn((27,2))
X = torch.arange(32*3).reshape((32,3)) % 27
C.shape, X.shape, C[X].shape
# if you understand this, you can explain why the % 27 is needed

(torch.Size([27, 2]), torch.Size([32, 3]), torch.Size([32, 3, 2]))

In [55]:
# CONCATENATE
X = torch.randn((2,3))
X, torch.cat((x, x), 0), torch.cat((x, x), 1)

(tensor([[ 0.5568, -0.8123,  1.1964],
         [ 0.8613, -1.3682, -0.7740]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3,  0,  1,  2,  3],
         [ 4,  5,  6,  7,  4,  5,  6,  7],
         [ 8,  9, 10, 11,  8,  9, 10, 11]]))

In [56]:
# UNBIND
t = torch.arange(6).reshape((2,3))
t, t.unbind(), t.unbind(1)

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 (tensor([0, 1, 2]), tensor([3, 4, 5])),
 (tensor([0, 3]), tensor([1, 4]), tensor([2, 5])))

In [57]:
t2 = torch.arange(12).reshape((2,3,2))
t2, t2.unbind()

(tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]]]),
 (tensor([[0, 1],
          [2, 3],
          [4, 5]]),
  tensor([[ 6,  7],
          [ 8,  9],
          [10, 11]])))